FROM debian:testing as release
LABEL maintainer="Andras Mitzki <andras.mitzki@balabit.com>, László Várady <laszlo.varady@balabit.com>"
LABEL org.opencontainers.image.source="https://github.com/syslog-ng/syslog-ng"

ARG PKG_TYPE=stable

RUN apt-get update -qq && apt-get install -y \
    wget \
    ca-certificates \
    gnupg2 \
    && rm -rf /var/lib/apt/lists/*

# should be able to ignore the following (2) lines
RUN wget -qO - https://ose-repo.syslog-ng.com/apt/syslog-ng-ose-pub.asc | gpg --dearmor > /usr/share/keyrings/ose-repo-archive-keyring.gpg && \
  echo "deb [signed-by=/usr/share/keyrings/ose-repo-archive-keyring.gpg] https://ose-repo.syslog-ng.com/apt/ ${PKG_TYPE} debian-testing" | tee --append /etc/apt/sources.list.d/syslog-ng-ose.list

# add a few tools for debugging; net-tools, tcpdump, telnet, ncat, curl
RUN apt-get update -qq && apt-get install -y \
    libdbd-mysql libdbd-pgsql libdbd-sqlite3 syslog-ng libjemalloc2 \
    net-tools tcpdump telnet ncat curl procps \
    && rm -rf /var/lib/apt/lists/*

# add a basic syslog-ng config file
# Note: This file is overwritten during deployment to ensure at least a base
# config exists.  In the event of any issues with the deployment, at least this
# config will help ensure syslog-ng starts and therefore will assist with debugging
# any issues.
ADD files/syslog-ng.conf /etc/syslog-ng/syslog-ng.conf

# add the API (note this file is generated by the build process)
ADD syslog_ng_api /usr/sbin/syslog_ng_api
RUN chmod 755 /usr/sbin/syslog_ng_api

# expose the following ports for docker testing
EXPOSE 514/udp
EXPOSE 514/tcp
EXPOSE 601/tcp
EXPOSE 6514/tcp

HEALTHCHECK --interval=2m --timeout=5s --start-period=30s CMD /usr/sbin/syslog-ng-ctl healthcheck --timeout 5
ENV LD_PRELOAD /usr/lib/x86_64-linux-gnu/libjemalloc.so.2

# entrypoint to run syslog-ng in the forground (-F) and to use a specific control file (-c <path>)
#ENTRYPOINT ["/usr/sbin/syslog-ng", "-F", "-c", "/var/lib/syslog-ng/ctl/syslog-ng.ctl"]
#ENTRYPOINT ["/usr/sbin/syslog-ng", "-F"]
# call wrapper.sh which handles starting syslog-ng and syslog_ng_api

ADD files/wrapper.sh /usr/sbin/wrapper.sh
RUN chmod 755 /usr/sbin/wrapper.sh
ENTRYPOINT ["wrapper.sh"]
